export const SET_YATOKEN = 'TOKEN/SET_YATOKEN';

export const CHANGE_SANDBOX = 'SANDBOX/CHANGE_SANDBOX';

export const GET_POOLS = 'POOLS/GET_POOLS';
export const REFRESH_POOLS = 'POOLS/REFRESH_POOLS';
export const OPEN_POOL = 'POOLS/OPEN_POOL'; 
export const CLOSE_POOL = 'POOLS/CLOSE_POOL'; 
export const SET_ACTIVE_POOL = 'POOLS/SET_ACTIVE_POOL';

export const SHOW_GET_POOLS_SPINNER = 'APP/SHOW_GET_POOLS_SPINNER';
export const HIDE_GET_POOLS_SPINNER = 'APP/HIDE_GET_POOLS_SPINNER';
export const SHOW_SEND_TASKS_SPINNER = 'APP/SHOW_SEND_TASKS_SPINNER';
export const HIDE_SEND_TASKS_SPINNER = 'APP/HIDE_SEND_TASKS_SPINNER';
export const SET_ERROR = 'APP/SET_ERROR';
export const RESET_ERROR = 'APP/RESET_ERROR';
export const SET_LOCAL_STORAGE = 'APP/SET_LOCAL_STORAGE';
export const SET_SPINNER = 'APP/SET_SPINNER';
export const SHOW_SPINNER = 'APP/SHOW_SPINNER';
export const HIDE_SPINNER = 'APP/HIDE_SPINNER';

export const READ_IMAGES = 'IMAGES/READ_IMAGES';
export const READ_IMAGES_FROM_POOL = 'IMAGES/READ_IMAGES_FROM_POOL';
export const REMOVE_DUPLICATE_NAMES = 'IMAGES/REMOVE_DUPLICATE_NAMES';
export const SET_DECISION = 'IMAGES/SET_DECISION';
export const SET_COMMENT = 'IMAGES/SET_COMMENT';
export const CHANGE_ALL = 'IMAGES/CHANGE_ALL';

export const CHECK_NAME_PATTERN = 'IMAGES/CHECK_NAME_PATTERN';
export const CHECK_IMAGES_SIZE = 'IMAGES/CHECK_IMAGE_SIZE';
export const CHECK_WHITE_AREA = 'IMAGES/CHECK_WHITE_AREA';
export const SEND_CHECKED_TASKS = 'IMAGES/SEND_CHECKED_TASKS';  